"""change photo in user to photo_url

Revision ID: 091ea23c9874
Revises: bf3763319c11
Create Date: 2023-01-11 08:32:40.268148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '091ea23c9874'
down_revision = 'bf3763319c11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
