"""add value column to vote table

Revision ID: 5c24f39536c1
Revises: 18deba3474b1
Create Date: 2022-12-02 16:32:44.042555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c24f39536c1'
down_revision = '18deba3474b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'value')
    # ### end Alembic commands ###
