"""v 7 add about to user

Revision ID: 943bbb97c8e3
Revises: 14b5c06c53d0
Create Date: 2023-01-09 17:47:47.619043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943bbb97c8e3'
down_revision = '14b5c06c53d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
