"""v 4 rename user to owner

Revision ID: 98212441d29f
Revises: f217644dfde1
Create Date: 2022-12-07 13:39:49.249382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98212441d29f'
down_revision = 'f217644dfde1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###
