"""v 3 add user and post relationship to comment table

Revision ID: f217644dfde1
Revises: 2da461650dcb
Create Date: 2022-12-07 12:49:35.156382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f217644dfde1'
down_revision = '2da461650dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
