name: Build and Deploy Code

on:
  push:
    branches:
      - "main"
  pull_requests:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to sean
        run: echo "hello sean"
